# Docker compose file that builds images and runs the containers needed for
# development. You need to have your MJKEY set in the environment.
#
# docker-compose \
#     -f ./docker/docker-compose.dev.yml \
#     build \
#         --build-arg MJKEY="$(cat ~/.mujoco/mjkey.txt)"

version: "2.4"
services:
  softlearning-dev-gpu:
    image: ${USER}-${IMAGE_NAME:-softlearning}:${IMAGE_TAG:-latest}-gpu
    container_name: ${USER}-softlearning-dev-gpu
    runtime: nvidia
    build:
      context: ../.
      dockerfile: docker/Dockerfile.softlearning.base.gpu
      cache_from:
        - ${IMAGE_NAME:-softlearning}:latest-gpu
      args:
        - MJKEY
    init: true
    working_dir: /root/softlearning-vice
    environment:
      - DISPLAY=:0
    ports:
      - "6006"  # Tensorboard
      - "5000"  # Viskit
      - "8888"  # Jupyter
    volumes: # host : container
       - ~/.config/gcloud:/root/.config/gcloud  # If using gcp, e.g. for gs
       - ~/.mujoco/mjkey.txt:/root/.mujoco/mjkey.txt
       - ..:/root/softlearning-vice
       - ~/ray_results/softlearning-dev-gpu:/root/ray_results
       - ../../dsuite:/root/dsuite
    command:
      - bash
    stdin_open: true
    tty: true
